---
- name: Enable and Start drpc
  service: name=storm-drpc state=started enabled=yes

- name: wait for drpc port
  wait_for: port={{storm_drpc_port}} state=started timeout={{ monasca_wait_for_period }}
  when: verify
