---
- include: stop_drpc.yml
  when: (ansible_host in storm_drpc_servers) or (ansible_hostname in storm_drpc_servers)

- include: stop_nimbus.yml
  when: storm_nimbus_enabled

- include: stop_supervisor.yml
  when: storm_supervisor_enabled
