---
- name: Restart drpc
  service: name=storm-drpc state=restarted
  when: (ansible_host in storm_drpc_servers) or (ansible_hostname in storm_drpc_servers) | bool and run_mode == 'Deploy'

- name: Restart Nimbus
  service: name=storm-nimbus state=restarted
  when: storm_nimbus_enabled | bool and run_mode == 'Deploy'

- name: Restart Supervisor
  service: name=storm-supervisor state=restarted
  when: storm_supervisor_enabled | bool and run_mode == 'Deploy'

- name: Restart Logviewer
  service: name=storm-logviewer state=restarted
  when: storm_logviewer_enabled | bool and run_mode == 'Deploy'

- name: Restart UI
  service: name=storm-ui state=restarted
  when: storm_ui_enabled | bool and run_mode == 'Deploy'
